name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      # Step 3: Install dependencies
      - name: Clean Install
        run: npm install --legacy-peer-deps

      # Step 4: Run Linter
      - name: Run Linter
        run: npm run lint

      # Step 5: Run Unit Tests
      - name: Run Tests
        run: npm test

      # Step 6: Build the application
      - name: Build
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
            ${{ secrets.CLERK_PUBLISHABLE_KEY }}
        run: npm run build

      # Step 7: Start the application in the background
      - name: Start Application
        run: npm run start &
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
            ${{ secrets.CLERK_PUBLISHABLE_KEY }}

      # Step 8: Wait for the application to be ready
      - name: Wait for Application to Start
        run: npx wait-on http://localhost:3000

      # Step 9: Run Cypress End-to-End Tests
      - name: Run Cypress Tests
        run: npx cypress run
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
            ${{ secrets.CLERK_PUBLISHABLE_KEY }}
          CYPRESS_BASE_URL: http://localhost:3000

      # Step 10: Stop the application
      - name: Stop Application
        run: |
          kill $(lsof -t -i:3000)
