name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      # Step 3: Install dependencies
      - name: Clean Install
        run: npm install --legacy-peer-deps

      # Step 4: Run Linter
      - name: Run Linter
        run: npm run lint

      # Step 5: Run Unit Tests
      - name: Run Tests
        run: npm test

      # Step 6: Build the application
      - name: Build
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
            ${{ secrets.CLERK_PUBLISHABLE_KEY }}
        run: npm run build

      # Step 7: Install XVFB
      - name: Install XVFB
        run: sudo apt-get install -y xvfb

      # Step 8: Start XVFB
      - name: Start XVFB
        run: Xvfb :99 -screen 0 1280x1024x24 &

      # Step 9: Run Cypress End-to-End Tests
      - name: Run Cypress Tests
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
            ${{ secrets.CLERK_PUBLISHABLE_KEY }}
          CYPRESS_BASE_URL: http://localhost:3000
        run: |
          export DISPLAY=:99
          npx cypress run
